// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.1008
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RPSLS.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("GameRules")]
    public partial class GameRulesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GameRules.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GameRules", "In order to poder ser el campeón mundial de RPSLS\r\nAs a jugador\r\nI want to poder " +
                    "practicar contra un programa", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ganador juego")]
        [NUnit.Framework.TestCaseAttribute("Piedra", "Piedra", "Empate", null)]
        [NUnit.Framework.TestCaseAttribute("Piedra", "Papel", "Pierdes", null)]
        [NUnit.Framework.TestCaseAttribute("Piedra", "Tijeras", "Ganas", null)]
        [NUnit.Framework.TestCaseAttribute("Piedra", "Lagarto", "Ganas", null)]
        [NUnit.Framework.TestCaseAttribute("Piedra", "Spock", "Pierdes", null)]
        [NUnit.Framework.TestCaseAttribute("Papel", "Piedra", "Ganas", null)]
        [NUnit.Framework.TestCaseAttribute("Papel", "Papel", "Empate", null)]
        [NUnit.Framework.TestCaseAttribute("Papel", "Tijeras", "Pierdes", null)]
        [NUnit.Framework.TestCaseAttribute("Papel", "Lagarto", "Pierdes", null)]
        [NUnit.Framework.TestCaseAttribute("Papel", "Spock", "Ganas", null)]
        [NUnit.Framework.TestCaseAttribute("Tijeras", "Papel", "Ganas", null)]
        [NUnit.Framework.TestCaseAttribute("Tijeras", "Lagarto", "Ganas", null)]
        [NUnit.Framework.TestCaseAttribute("Tijeras", "Piedra", "Pierdes", null)]
        [NUnit.Framework.TestCaseAttribute("Tijeras", "Tijeras", "Empate", null)]
        [NUnit.Framework.TestCaseAttribute("Tijeras", "Spock", "Pierdes", null)]
        [NUnit.Framework.TestCaseAttribute("Lagarto", "Piedra", "Pierdes", null)]
        [NUnit.Framework.TestCaseAttribute("Lagarto", "Papel", "Ganas", null)]
        [NUnit.Framework.TestCaseAttribute("Lagarto", "Tijeras", "Pierdes", null)]
        [NUnit.Framework.TestCaseAttribute("Lagarto", "Lagarto", "Empate", null)]
        [NUnit.Framework.TestCaseAttribute("Lagarto", "Spock", "Ganas", null)]
        [NUnit.Framework.TestCaseAttribute("Spock", "Piedra", "Ganas", null)]
        [NUnit.Framework.TestCaseAttribute("Spock", "Papel", "Pierdes", null)]
        [NUnit.Framework.TestCaseAttribute("Spock", "Tijeras", "Ganas", null)]
        [NUnit.Framework.TestCaseAttribute("Spock", "Lagarto", "Pierdes", null)]
        [NUnit.Framework.TestCaseAttribute("Spock", "Spock", "Empate", null)]
        public virtual void GanadorJuego(string opcionJugador, string opcionCPU, string resultado, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ganador juego", exampleTags);
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given(string.Format("escojo la opcion \'{0}\'", opcionJugador), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
 testRunner.When(string.Format("CPU escoge la opcion \'{0}\'", opcionCPU), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.Then(string.Format("veo el resultado \'{0}\'", resultado), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
